### ISSUE TITLE
Errors reported during initial deploy

### ISSUE THREAD

**Issue by gilzow** [platformsh-templates/drupal9#114]
### Describe the bug

Lines [81-87 in .platform.app.yaml](https://github.com/platformsh-templates/drupal9/blob/master/.platform.app.yaml#L81-L87) contains a series of drush commands in the deploy hook. In existing site, these commands make sense and are beneficial. However, in a brand new deploy of a drupal project, Drupal is not installed and these commands trigger an error in the log. This can cause confusion for new users as it appears the deploy failed or encountered issues. 

### Include some logs

```
    Executing deploy hook for application drupal
      Created Drush configuration file: /app/.drush/drush.yml
      W:  [success] Cache rebuild complete.
      W: 
      W: In BootstrapHook.php line 36:
      W:                                                                       
      W:   Bootstrap failed. Run your command with -vvv for more information.  
      W:                                                                       
      W: 
```

### Reproducing

1. create new project in platform.sh console
2. select drupal8 template
3. choose name, environment, region
4. click "create project"
5. view log from deployment of environment

### Expected behavior

No errors in an initial deployment

### Your environment

default creation a Drupal9 template from the template chooser.

### Additional context

Suggest changing deploy to something like the following:

```yaml
    deploy: |
        set -e
        php ./drush/platformsh_generate_drush_yml.php
        cd web
        if [ -n "$(drush status bootstrap)" ]; then
          drush -y cache-rebuild
          drush -y updatedb
          if [ -n "$(ls $(drush php:eval "echo realpath(Drupal\Core\Site\Settings::get('config_sync_directory'));")/*.{yml,yaml} 2>/dev/null)" ]; then
            drush -y config-import
          else
            echo "No config to import. Skipping."
          fi
        else
          echo "Drupal not installed. Skipping standard Drupal deploy steps"
        fi
```

We use `drush status bootstrap` to determine if drupal is installed. `status bootstrap` if successful will return `Drupal bootstrap : Successful` or nothing if bootstrap is unable to complete. If bootstrap is able to complete, only then do we continue with the other drush commands.

**Comment by gilzow** [comment]
I finally found some docs on the [standards for naming configuration files](https://www.drupal.org/docs/develop/coding-standards/configuration-file-coding-standards). 

> The configuration file name is equal to the unique configuration name with .yml extension.

We can change the above suggestion from `*.{yaml,yml}` to `*.yml`

**Comment by rfay** [comment]
I'd welcome this change.
