### ISSUE TITLE
Add a working github actions workflow

### ISSUE THREAD

**Issue by andrewfandrew** [platformsh-templates/drupal9#117]
### What in this template can be improved or added as a feature?

Add a .github directory along with other necessary files to run some basic tests on push and pull requests. 

### What exactly should be updated?

Add a .github/workflows/ci.yml file. This will specify the actions and will spin up an ubuntu VM. Since the template includes support for the DDEV project, the workflow should integrate with ddev and use the same containers. 

### How important is this feature to you?

I have started using this setup in my own Platform.sh Drupal 9 app which is based on this template. I wanted to share it so that others can utilise the benefits of automated testing on their Drupal site.

**Comment by gilzow** [comment]
Closed via #135
