### ISSUE TITLE
Lando environment settings

### ISSUE THREAD

**Issue by tormi** [platformsh-templates/drupal9#18]
It would be useful to add default database etc settings for Lando environment, something like this: https://github.com/wunderio/drupal-project/blob/master/web/sites/default/settings.lando.php

**Comment by pirog** [comment]
@tormi if you are using the `platformsh` recipe in Lando then the `settings.platformsh.php` file _should_ work the same as it does on platform itself eg it will automatically handle your database connection, etc. You can, of course still use a `settings.lando.php` but it should not be necessary to get a platform site running out of the box.

It's also worth checking out the pattern here:
https://docs.lando.dev/config/platformsh.html#overriding-application-config
which will allow you to override a good deal of platform configuration with things that make more sense for local dev. 

Note that this template itself already does some of this on its own
https://github.com/platformsh-templates/drupal9/blob/master/.lando.upstream.yml#L20

**Comment by tormi** [comment]
Thanks!
